Add delete event functionality
stevent-team/stevent pull request #268
Opened 2022-04-14 02:59 UTC by Prydeton

![image](https://user-images.githubusercontent.com/42962051/163305043-47021b0b-a3b6-4a80-81d5-f743bfa9c9cf.png)

Adding images so I can be like @giraugh

2022-04-14 09:59 UTC, giraugh requested changes
Admittedly a couple of pedantic comments but also one big one. Notably I think we need to delete related ticket resources when deleting an event to prevent zombie tickets 🧟

2022-04-14 09:59 UTC, giraugh commented on backend/src/graphql/resolvers/event/mutations.js
> +
I think we also need to delete `TicketTemplates` and their connected `Tickets` here too. Otherwise we will get Tickets that try to render event details that don't exist.

2022-04-14 09:59 UTC, giraugh commented on frontend/src/pages/Dashboards/EventDash/pages/Cancel/Cancel.js
> +import DELETE_EVENT_MUTATION from "/src/services/graphql/mutations/deleteEventMutation"
These mutations should be exported from the index so that you can do
```js
import { DELETE_EVENT_MUTATION } from "/src/services/graphql/mutations"
```

2022-04-14 09:59 UTC, giraugh commented on frontend/src/pages/Dashboards/EventDash/pages/Cancel/Cancel.js
> +  const [{ fetching, data: { error } = {}}, deleteEvent] = useMutation(DELETE_EVENT_MUTATION)
Im not 100% confident but I don't think the error is in the data object? I think this should be
```js
const [{ fetching, error }, deleteEvent] = ...
```

2022-04-14 09:59 UTC, giraugh commented on frontend/src/pages/Dashboards/EventDash/pages/Cancel/Cancel.js
> +    return
It doesn't have any syntactical difference but an indent here would be 😗:ok_hand:

2022-04-15 00:51 UTC, giraugh commented
Soon:tm:

2022-04-18 07:45 UTC, Prydeton commented
No longer being used since backend was moved to prisma

2022-04-18 07:45 UTC, closed without merging